name: ms_graph_client
description: Microsoft Graph API client
version: 0.0.4
author: unger1984
homepage: https://github.com/unger1984

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

